[package]
name = "tokio-interval"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "=1.27", features = ["sync", "macros", "time", "rt-multi-thread"] }
pin-project = "1.0"